### ISSUE TITLE
Error: Command failed with exit code 1: git config user.name

### ISSUE THREAD

**Issue by eJayYoung** [geongeorge/Git-User-Switch#15]
hi, when I'was not set git config user info ,  `execa.command` will throw a Error: `Command failed with exit code 1: git config user.name`

I found it's caused by `fetchUser` below `execa.command` not handling errors
- https://github.com/geongeorge/Git-User-Switch/blob/master/src/lib/fetchUser.js#L13
- https://github.com/geongeorge/Git-User-Switch/blob/master/src/lib/fetchUser.js#L16
- https://github.com/geongeorge/Git-User-Switch/blob/master/src/lib/fetchUser.js#L23
- https://github.com/geongeorge/Git-User-Switch/blob/master/src/lib/fetchUser.js#L26

I know `fetchUser` is just for display current git user info which is get from `git config user.xxx`，
But if not initialized git config user，like [Troubleshoot](https://github.com/geongeorge/Git-User-Switch#troubleshoot), user experience is not feeling good.

a [PR](https://github.com/geongeorge/Git-User-Switch/pull/16) to fix it.

**Comment by eJayYoung** [comment]
Otherwise，I've read the source code, found `git-user reset` will only reset user info in the `Conf` store，but git config user info is still exist. It's puzzle me.

In my opinion，I may want to remove `git config` user info as well. or add another command like `remove` for sync remove local git config user info

**Comment by geongeorge** [comment]
I have merged the https://github.com/geongeorge/Git-User-Switch/pull/16 

And about removing the git config user, What would happen if we git-user remove the global user? Wouldn't it remove the user from the main config

**Comment by eJayYoung** [comment]
I agree with 

>  Wouldn't it remove the user from the main config

so, what make me puzzle is,  while `git-user --reset` the `Conf` store,  then I run `git-user` command，[`initUser`](https://github.com/geongeorge/Git-User-Switch/blob/master/src/lib/initUser.js#L6) will get local git config user info as initialization data without any prompt. 

For new users of `git-user`: 

- add a prompt selection when initUser will be friendly
- add explain about `git-user` command operating principle in README 
  - eg: `git-user` store user info list with [conf](https://github.com/sindresorhus/conf), which `Conf` store's storage path in macOS is：~/Library/Preferences/git-user-switch-nodejs/config.json, is not sync with local git config of user, only when `selectUser` will cover the user git config

**Comment by eJayYoung** [comment]
I got the [`fetchUser` prompt ](https://github.com/geongeorge/Git-User-Switch/blob/master/src/cli.js#L62) 
 ```bash
Current git user(local) is xxx:xxxxxxx@xxx.com
```
 maybe acceptable to the users
