### ISSUE TITLE
`git-user` command does not work reliably

### ISSUE THREAD

**Issue by zxt-tzx** [geongeorge/Git-User-Switch#17]
In the example below, the setting does not work at all

<img width="359" alt="image" src="https://user-images.githubusercontent.com/67887489/163938105-44c1b4a3-5dd4-43cf-9b16-861aae42258b.png">

I have also experienced a weird edge case where `git-user` only sets user.name, but user.email remains unchanged.

**Comment by eJayYoung** [comment]
This problem maybe come with if your local or global git user info is inComplete

First, you can check your local git user info in git project directory with
`git config --list`

The first `user.name` or `user.email` to appear is git config global user info
Then the second  `user.name` or `user.email` to appear is git config local user info

You can reset git user info with below command
- gloabl: `git config --global --unset user.name`, `git config --global --unset user.email`
- local: `git config --unset user.name`, `git config --unset user.email`

After that, try `git-user` again, then you set the git config in right way

**Comment by geongeorge** [comment]
Weird, but I noticed this issue as well. For my particular use case, I don't care if I have to use this command twice, but there is something wrong definitely.

**Comment by geongeorge** [comment]
@eJayYoung You're right! This was because I did not have a global user setup. You can use git-user for that as well. 
Just run: `git user --global`
and setup the global user.
