### ISSUE TITLE
Feature request: switch user.signingKey

### ISSUE THREAD

**Issue by spenserblack** [geongeorge/Git-User-Switch#2]
This looks like a pretty cool project! :smile:
I would like to use this, as I switch git credentials often, but I use a signing key.

Would it be possible to set an optional signing key when creating a user, and switch to that signing key if it exists?

**Comment by spenserblack** [comment]
Ref: https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

**Comment by geongeorge** [comment]
@spenserblack This should be actually fairly easy.
But considering my limited knowledge about signing keys I'll read about it and then add the feature

But feel free to raise a PR. The code is pretty straight foreward

**Comment by spenserblack** [comment]
No problem, I'll make a PR :smiley:
