### ISSUE TITLE
See current user in PS1

### ISSUE THREAD

**Issue by zexa** [geongeorge/Git-User-Switch#5]
It would be nice to have a way to see the current user in my PS1 when I'm in a git directory. 

Perhaps anyone here has a solution for that?

**Comment by geongeorge** [comment]
This should be actually very easy. Follow this issue. I'll have an update in a few days

**Comment by beetcb** [comment]
I also agree that during the initialization process, a new feature could be added to get existing git users, including the `local` and `global`

**Comment by geongeorge** [comment]
A few days turned into almost a year! :|

**Comment by geongeorge** [comment]
Fixed now
![image](https://user-images.githubusercontent.com/29296982/162694658-9e0e39a8-d126-40db-937d-5c1ef6c9b33e.png)

**Comment by geongeorge** [comment]
Fixed in 0.6.0 
![image](https://user-images.githubusercontent.com/29296982/162694793-f99917c8-7249-4664-8697-3d63d7f1980e.png)
